import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { formatMoney } from '@/lib/money';
import type { Org } from '@/lib/types';

interface DocLine {
  name: string;
  detail: string; // e.g. SKU
  quantity: number;
  unitCents: number;
}

interface DocOptions {
  org: Org;
  title: string; // "Purchase Order" | "Invoice"
  docNumber: string;
  date: string;
  partyLabel: string; // "Supplier" | "Bill to"
  partyName: string;
  lines: DocLine[];
  taxRate: number; // percent
  notes?: string;
  meta?: { label: string; value: string }[];
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function buildDocumentHtml(opts: DocOptions): string {
  const { org, lines } = opts;
  const subtotal = lines.reduce((sum, l) => sum + l.quantity * l.unitCents, 0);
  const tax = Math.round((subtotal * opts.taxRate) / 100);
  const total = subtotal + tax;
  const money = (c: number) => formatMoney(c, org.currency);

  const rows = lines
    .map(
      (l, i) => `
      <tr>
        <td class="muted">${i + 1}</td>
        <td><strong>${escapeHtml(l.name)}</strong><br /><span class="muted">${escapeHtml(l.detail)}</span></td>
        <td class="num">${l.quantity}</td>
        <td class="num">${money(l.unitCents)}</td>
        <td class="num">${money(l.quantity * l.unitCents)}</td>
      </tr>`
    )
    .join('');

  const metaRows = (opts.meta ?? [])
    .map((m) => `<div><span class="muted">${escapeHtml(m.label)}:</span> ${escapeHtml(m.value)}</div>`)
    .join('');

  const logo = org.logo_url
    ? `<img src="${escapeHtml(org.logo_url)}" style="height:56px;max-width:160px;object-fit:contain" />`
    : `<div class="logo-fallback">${escapeHtml(org.name.slice(0, 1).toUpperCase())}</div>`;

  return `
  <html><head><meta charset="utf-8" />
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #17202a; margin: 32px; font-size: 13px; }
    .head { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 28px; }
    .logo-fallback { width:56px;height:56px;border-radius:12px;background:#1f6feb;color:#fff;font-size:28px;
      display:flex;align-items:center;justify-content:center;font-weight:700; }
    h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: 0.5px; }
    .muted { color: #6b7280; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.6px; color: #6b7280;
      border-bottom: 2px solid #e5e7eb; padding: 8px 6px; }
    td { padding: 10px 6px; border-bottom: 1px solid #f0f1f3; vertical-align: top; }
    .num { text-align: right; white-space: nowrap; }
    th.num { text-align: right; }
    .totals { margin-top: 16px; margin-left: auto; width: 260px; }
    .totals div { display: flex; justify-content: space-between; padding: 4px 6px; }
    .totals .grand { border-top: 2px solid #17202a; font-weight: 700; font-size: 15px; margin-top: 6px; padding-top: 8px; }
    .notes { margin-top: 28px; padding: 12px; background: #f8f9fb; border-radius: 8px; }
    .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; text-align: center; }
  </style></head><body>
    <div class="head">
      <div>
        ${logo}
        <h1 style="margin-top:12px">${escapeHtml(org.name)}</h1>
      </div>
      <div style="text-align:right">
        <h1>${escapeHtml(opts.title)}</h1>
        <div class="muted">${escapeHtml(opts.docNumber)}</div>
        <div class="muted">${escapeHtml(opts.date)}</div>
        ${metaRows}
      </div>
    </div>
    <div><span class="muted">${escapeHtml(opts.partyLabel)}:</span> <strong>${escapeHtml(opts.partyName)}</strong></div>
    <table>
      <thead><tr><th>#</th><th>Item</th><th class="num">Qty</th><th class="num">Unit</th><th class="num">Amount</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="totals">
      <div><span class="muted">Subtotal</span><span>${money(subtotal)}</span></div>
      <div><span class="muted">Tax (${opts.taxRate}%)</span><span>${money(tax)}</span></div>
      <div class="grand"><span>Total</span><span>${money(total)}</span></div>
    </div>
    ${opts.notes ? `<div class="notes"><strong>Notes</strong><br />${escapeHtml(opts.notes)}</div>` : ''}
    <div class="footer">Generated by StockRoom · ${escapeHtml(new Date().toLocaleString())}</div>
  </body></html>`;
}

/** Render the document to a PDF file and open the platform share sheet. */
export async function printAndShare(html: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf' });
  }
}
